#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

while IFS=':' read -r line; do
    username=$(awk -F':' '{print $1}' <<< "$line")
    gid=$(awk -F':' '{print $4}' <<< "$line")
    home=$(awk -F':' '{print $6}' <<< "$line")
    shell=$(awk -F':' '{print $NF}' <<< "$line")
    uid=$(awk -F':' '{print $3}' <<< "$line")
    password=$(awk -F':' '{print $2}' <<< "$line")
    info=$(awk -F':' '{print $5}' <<< "$line")
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
