#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

while IFS=':' read -r line; do
    fields=($line)
    username="${fields[0]}"
    password="${fields[1]}"
    uid="${fields[2]}"
    gid="${fields[3]}"
    info="${fields[4]}"
    home="${fields[5]}"
    shell="${fields[6]}"
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
