#!/usr/bin/env bash
#loop 10 iterations and three especific conditionals
counter=1
while ((counter <= 10)); do
  if [ $counter -eq 4 ]; then
    printf "%s\n" "bad luck"
  elif [ $counter -eq 8 ]; then
    printf "%s\n" "good luck"
  else
    printf "%s\n" "Best School"
  fi
  ((counter++))
done
