#!/usr/bin/env bash
# This scripts configures an ubuntu server with;
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

sudo su <<EOF
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.new
sed -i 's/.*facebook.com//g' ~/hosts.new
sed -i '1 a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
exit
EOF
